#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2013 Samsung Electronics.  All Rights Reserved.
#
# FS QA Test No. generic/022
#
# Delayed allocation collapse range tests
# This testcase is one of the 4 testcases which tries to
# test various corner cases for fcollapse range functionality over different
# type of extents. These tests are based on generic/255 test case.
# For the type of tests, check the description of _test_generic_punch
# in common/rc.
. ./common/preamble
_begin_fstest auto quick prealloc punch collapse

# Import common functions.
# we need to include common/punch to get defination fo filter functions
. ./common/filter
. ./common/punch

# real QA test starts here
_supported_fs generic

_require_test
_require_xfs_io_command "fpunch"
_require_xfs_io_command "falloc"
_require_xfs_io_command "fiemap"
_require_xfs_io_command "fcollapse"

testfile=$TEST_DIR/$seq.$$

_test_generic_punch -d falloc fpunch fcollapse fiemap _filter_hole_fiemap $testfile
_check_test_fs

status=0
exit
