#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Dmitry Monakhov.  All Rights Reserved.
#
# FS QA Test No. 036
#
# CVE-2014-8086
# Run aio-dio-fcntl-race - test aio write race with O_DIRECT toggle
#
. ./common/preamble
_begin_fstest auto aio rw stress

# Import common functions.
. ./common/filter

# real QA test starts here

_supported_fs generic
_require_test

_run_aiodio aio-dio-fcntl-race

_check_dmesg _filter_aiodio_dmesg

exit $status
