#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2004 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 088
#
# test out CAP_DAC_OVERRIDE and CAP_DAC_SEARCH code in 
# xfs_iaccess(ip,mode,cr)
#
seqfull=$0
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

_filter()
{
    _filter_test_dir | sed -e '/----------/d'
}

# real QA test starts here
_supported_fs generic
_require_test

path=$TEST_DIR/t_access
$here/src/t_access_root $path | tee $seqres.full | _filter

# success, all done
status=0
exit
