#! /bin/bash
# FS QA Test No. 093
#
# Test clearing of capabilities on write.
#
#-----------------------------------------------------------------------
# Copyright (c) 2000-2004 Silicon Graphics, Inc.  All Rights Reserved.
# Copyright (c) 2017 Google, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq

here=`pwd`
tmp=/tmp/$$
status=1	# FAILure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/attr

_cleanup()
{
    [ -n "$TEST_DIR" ] && rm -f $file
}

filefilter()
{
    sed -e "s#$file#file#"
}

# real QA test starts here
_supported_fs generic
_supported_os Linux

_require_test
_require_attrs
_require_user
_require_test_program "writemod"

rm -f $seqres.full

echo "QA output created by $seq"
echo ""
file=$TEST_DIR/$seq.file

rm -f $file
touch $file

echo "**** Verifying that appending to file clears capabilities ****"
setcap cap_chown+ep $file
getcap $file | filefilter
echo data1 >> $file
cat $file
getcap $file | filefilter
echo

echo "**** Verifying that appending to file doesn't clear other xattrs ****"
setcap cap_chown+ep $file
$SETFATTR_PROG -n trusted.name -v value $file
echo data2 >> $file
cat $file
$GETFATTR_PROG -m '^trusted\.*' --absolute-names $file | filefilter

echo "**** Verifying that chmod doesn't affect open file descriptors ****"
rm -f $file
touch $file
chown $qa_user $file
chmod ugo+w $TEST_DIR
su $qa_user -c "src/writemod $file" | filefilter
cat $file

# success, all done
status=0
exit
