#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015 Facebook.  All Rights Reserved.
#
# FS QA Test No. 094
#
# Run the fiemap (file extent mapping) tester with preallocation enabled
#
. ./common/preamble
_begin_fstest auto quick prealloc

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs generic
_require_scratch
_require_odirect
_require_xfs_io_command "fiemap"
_require_xfs_io_command "falloc"

_scratch_mkfs > /dev/null 2>&1
_scratch_mount > /dev/null 2>&1

fiemapfile=$SCRATCH_MNT/$seq.fiemap

_require_test_program "fiemap-tester"

# FIEMAP test doesn't like finding unwritten blocks after it punches out
# a partial rt extent.
test "$FSTYP" = "xfs" && \
	_require_file_block_size_equals_fs_block_size $SCRATCH_MNT

seed=`date +%s`

echo "using seed $seed" >> $seqres.full

echo "fiemap run with sync"
$here/src/fiemap-tester -q -S -s $seed -r 200 $fiemapfile 2>&1 | \
	tee -a $seqres.full

echo "fiemap run without sync"
$here/src/fiemap-tester -q -s $seed -r 200 $fiemapfile 2>&1 | \
	tee -a $seqres.full

status=0
exit
