#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 119
#
# Reflinking two sets of files together:
#   - Reflink identical parts of two identical files
#   - Reflink identical parts of two other identical files
#   - Reflink identical parts of all four files
#   - Check that we end up with identical contents
#
. ./common/preamble
_begin_fstest auto quick clone

# Override the default cleanup function.
_cleanup()
{
    cd /
    rm -rf $tmp.* $testdir
}

# Import common functions.
. ./common/filter
. ./common/reflink

# real QA test starts here
_require_test_reflink
_require_arbitrary_fileset_reflink

testdir=$TEST_DIR/test-$seq
rm -rf $testdir
mkdir $testdir

echo "Create the original files"
blksz=65536
_pwrite_byte 0x61 0 $((blksz * 8)) $testdir/file1 >> $seqres.full
_pwrite_byte 0x62 0 $((blksz * 8)) $testdir/file2 >> $seqres.full
_pwrite_byte 0x63 0 $((blksz * 8)) $testdir/file3 >> $seqres.full
_pwrite_byte 0x64 0 $((blksz * 8)) $testdir/file4 >> $seqres.full
_test_cycle_mount

md5sum $testdir/file1 | _filter_test_dir
md5sum $testdir/file2 | _filter_test_dir
md5sum $testdir/file3 | _filter_test_dir
md5sum $testdir/file4 | _filter_test_dir

_compare_range $testdir/file1 0 $testdir/file2 0 $((blksz * 8)) \
       || echo "Files 1-2 do not match (intentional)"

_compare_range $testdir/file1 0 $testdir/file3 0 $((blksz * 8)) \
       || echo "Files 1-3 do not match (intentional)"

_compare_range $testdir/file1 0 $testdir/file4 0 $((blksz * 8)) \
       || echo "Files 1-4 do not match (intentional)"

echo "Reflink the first four blocks together, 1-2 3-4"
free_before=$(stat -f -c '%a' $testdir)
_reflink_range $testdir/file1 0 $testdir/file2 0 $((blksz * 4)) >> $seqres.full
_reflink_range $testdir/file3 0 $testdir/file4 0 $((blksz * 4)) >> $seqres.full
_test_cycle_mount
free_after=$(stat -f -c '%a' $testdir)
echo "freesp changed by $free_before -> $free_after" >> $seqres.full

echo "Compare sections"
md5sum $testdir/file1 | _filter_test_dir
md5sum $testdir/file2 | _filter_test_dir
md5sum $testdir/file3 | _filter_test_dir
md5sum $testdir/file4 | _filter_test_dir

_compare_range $testdir/file1 0 $testdir/file2 0 $((blksz * 4)) \
       || echo "Sections of file 1-2 do not match"

_compare_range $testdir/file1 0 $testdir/file3 0 $((blksz * 4)) \
       || echo "Sections of file 1-3 do not match (intentional)"

_compare_range $testdir/file1 0 $testdir/file4 0 $((blksz * 4)) \
       || echo "Sections of file 1-4 do not match (intentional)"

_compare_range $testdir/file2 0 $testdir/file3 0 $((blksz * 4)) \
       || echo "Sections of file 2-3 do not match (intentional)"

_compare_range $testdir/file2 0 $testdir/file4 0 $((blksz * 4)) \
       || echo "Sections of file 2-4 do not match (intentional)"

_compare_range $testdir/file3 0 $testdir/file4 0 $((blksz * 4)) \
       || echo "Sections of file 3-4 do not match"

echo "Reflink the first two blocks together, 1-3 1-4"
free_before=$(stat -f -c '%a' $testdir)
_reflink_range $testdir/file1 0 $testdir/file3 0 $((blksz * 2)) >> $seqres.full
_reflink_range $testdir/file1 0 $testdir/file4 0 $((blksz * 2)) >> $seqres.full
_test_cycle_mount
free_after=$(stat -f -c '%a' $testdir)
echo "freesp changed by $free_before -> $free_after" >> $seqres.full

echo "Compare sections"
md5sum $testdir/file1 | _filter_test_dir
md5sum $testdir/file2 | _filter_test_dir
md5sum $testdir/file3 | _filter_test_dir
md5sum $testdir/file4 | _filter_test_dir

_compare_range $testdir/file1 0 $testdir/file2 0 $((blksz * 2)) \
       || echo "Sections of files 1-2 do not match"

_compare_range $testdir/file1 0 $testdir/file3 0 $((blksz * 2)) \
       || echo "Sections of files 1-3 do not match"

_compare_range $testdir/file1 0 $testdir/file4 0 $((blksz * 2)) \
       || echo "Sections of files 1-4 do not match"

_compare_range $testdir/file2 0 $testdir/file3 0 $((blksz * 2)) \
       || echo "Sections of files 2-3 do not match"

_compare_range $testdir/file2 0 $testdir/file4 0 $((blksz * 2)) \
       || echo "Sections of files 2-4 do not match"

_compare_range $testdir/file3 0 $testdir/file4 0 $((blksz * 2)) \
       || echo "Sections of files 3-4 do not match"

echo "Compare previously reflinked sections"
_compare_range $testdir/file1 $((blksz * 2)) $testdir/file2 \
		$((blksz * 2)) $((blksz * 2)) \
       || echo "Sections of file 1-2 do not match"

_compare_range $testdir/file1 $((blksz * 2)) $testdir/file3 \
		$((blksz * 2)) $((blksz * 2)) \
       || echo "Sections of file 1-3 do not match (intentional)"

_compare_range $testdir/file1 $((blksz * 2)) $testdir/file4 \
		$((blksz * 2)) $((blksz * 2)) \
       || echo "Sections of file 1-4 do not match (intentional)"

_compare_range $testdir/file2 $((blksz * 2)) $testdir/file3 \
		$((blksz * 2)) $((blksz * 2)) \
       || echo "Sections of file 2-3 do not match (intentional)"

_compare_range $testdir/file2 $((blksz * 2)) $testdir/file4 \
		$((blksz * 2)) $((blksz * 2)) \
       || echo "Sections of file 2-4 do not match (intentional)"

_compare_range $testdir/file3 $((blksz * 2)) $testdir/file4 \
		$((blksz * 2)) $((blksz * 2)) \
       || echo "Sections of file 3-4 do not match"

# success, all done
status=0
exit
