#! /bin/bash
# FS QA Test No. 159
#
# Check that we can't reflink immutable files
#
#-----------------------------------------------------------------------
# Copyright (c) 2015, Oracle and/or its affiliates.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -rf $tmp.* $testdir1
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/attr
. ./common/reflink

# real QA test starts here
_supported_os Linux
_require_test_lsattr
_require_test_reflink

rm -f $seqres.full

echo "Format and mount"
testdir1="$TEST_DIR/test-$seq"
rm -rf $testdir1
mkdir $testdir1

echo "Create the original files"
blksz="$(_get_block_size $testdir1)"
blks=1000
margin='7%'
sz=$((blksz * blks))
free_blocks0=$(stat -f $testdir1 -c '%f')
nr=4
filesize=$((blksz * nr))
_pwrite_byte 0x61 0 $sz $testdir1/file1 >> $seqres.full
_pwrite_byte 0x61 0 $sz $testdir1/file2 >> $seqres.full
sync

do_filter_output()
{
	_filter_test_dir | sed -e 's/Operation not permitted/Permission denied/g'
}

echo "Try reflink on immutable files"
$CHATTR_PROG +i $testdir1/file1 $testdir1/file2
_reflink_range $testdir1/file1 0 $testdir1/file2 0 $blksz 2>&1 | do_filter_output
$CHATTR_PROG -i $testdir1/file1 $testdir1/file2

# success, all done
status=0
exit
