#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2010 Eric Sandeen.  All Rights Reserved.
#
# FS QA Test No. 223
#
# File alignment tests
#
. ./common/preamble
_begin_fstest auto quick

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs generic

_require_scratch
_require_xfs_io_command "falloc"

BLOCKSIZE=4096

for SUNIT_K in 8 16 32 64 128; do
	let SUNIT_BYTES=$SUNIT_K*1024
	let SUNIT_BLOCKS=$SUNIT_BYTES/$BLOCKSIZE

	echo "=== mkfs with su $SUNIT_BLOCKS blocks x 4 ==="
	_scratch_mkfs_geom $SUNIT_BYTES 4 $BLOCKSIZE >> $seqres.full 2>&1
	_scratch_mount

	# This test checks for stripe alignments of space allocations on the
	# filesystem.  Make sure all files get created on the main device,
	# which for XFS means no rt files.
	test "$FSTYP" = "xfs" && \
		_xfs_force_bdev data $SCRATCH_MNT

	for SIZE_MULT in 1 2 8 64 256; do
		let SIZE=$SIZE_MULT*$SUNIT_BYTES

		echo "=== Testing size ${SIZE_MULT}*${SUNIT_K}k on ${SUNIT_K}k stripe ==="
		for FILE in 1 2 3 4; do
			$XFS_IO_PROG -f -c "falloc 0 $SIZE" \
				$SCRATCH_MNT/file-$FILE-$SIZE-falloc \
					>> $seqres.full 2>&1
			$XFS_IO_PROG -f -c "pwrite -b $SIZE 0 $SIZE" \
				$SCRATCH_MNT/file-$FILE-$SIZE-write \
					>> $seqres.full 2>&1
			$here/src/t_stripealign $SCRATCH_MNT/file-$FILE-$SIZE-falloc \
				$SUNIT_BLOCKS | _filter_scratch
			$here/src/t_stripealign $SCRATCH_MNT/file-$FILE-$SIZE-write \
				$SUNIT_BLOCKS | _filter_scratch
		done
	done

	echo "=== Testing size 1g falloc on ${SUNIT_K}k stripe ==="
	$XFS_IO_PROG -f -c "falloc 0 1g" \
	    $SCRATCH_MNT/file-1g-falloc >> $seqres.full 2>&1
	$here/src/t_stripealign $SCRATCH_MNT/file-1g-falloc $SUNIT_BLOCKS \
	    | _filter_scratch

	rm -f $SCRATCH_MNT/file-1g-falloc | _filter_scratch

	echo "=== Testing size 1073745920 falloc on ${SUNIT_K}k stripe ==="
	$XFS_IO_PROG -f -c "falloc 0 1073745920" \
		$SCRATCH_MNT/file-1073745920-falloc >> $seqres.full 2>&1
	$here/src/t_stripealign $SCRATCH_MNT/file-1073745920-falloc \
		$SUNIT_BLOCKS | _filter_scratch

	_scratch_unmount
done

status=0
exit
