#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2010 Christoph Hellwig.  All Rights Reserved.
#
# FS QA Test No. 246
#
# Check that truncation after failed writes does not zero too much data.
#
# Based on a bug report and testcase from
# Marius Tolzmann <tolzmann@molgen.mpg.de>
#
. ./common/preamble
_begin_fstest auto quick rw

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs generic
_require_test

file=$TEST_DIR/mmap-writev

# Override the default cleanup function.
_cleanup()
{
	rm -rf $file
	rm -rf $file.NEW
}

echo -n "cccccccccc" > $file
$here/src/t_mmap_writev $file $file.NEW
od -t x2 $file.NEW

status=0
exit $status
