#! /bin/bash
# FS QA Test No. 280
#
# Test quota vs. suspend/freeze deadlock, 
# dcdbed85 quota: Fix deadlock with suspend and quotas
#
#-----------------------------------------------------------------------
# Copyright (c) 2012 Red Hat, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/quota

_require_scratch
_require_quota
_require_freeze

# real QA test starts here

# Modify as appropriate.
_supported_os Linux
_supported_fs generic

rm -f $seqres.full

_scratch_unmount 2>/dev/null
_scratch_mkfs >> $seqres.full 2>&1
_scratch_mount "-o usrquota,grpquota"
quotacheck -u -g $SCRATCH_MNT 2>/dev/null
quotaon $SCRATCH_MNT 2>/dev/null
xfs_freeze -f $SCRATCH_MNT
setquota -u root 1 2 3 4 $SCRATCH_MNT &
pid=$!
sleep 1
xfs_freeze -u $SCRATCH_MNT
wait $pid
_scratch_unmount

# Failure comes in the form of a deadlock.

# success, all done
status=0
exit
