#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2011 Oracle Inc.  All Rights Reserved.
# Copyright (c) 2011 Red Hat.  All Rights Reserved.
#
# FS QA Test No. 285
#
# SEEK_DATA/SEEK_HOLE sanity tests.
#
# Improved by Jeff.liu@oracle.com
# Creater: josef@redhat.com
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

_supported_fs generic
_supported_os Linux

_require_test
_require_seek_data_hole

BASE_TEST_FILE=$TEST_DIR/seek_sanity_testfile

_require_test_program "seek_sanity_test"

_cleanup()
{
	eval "rm -f $BASE_TEST_FILE.*"
}

_run_seek_sanity_test $BASE_TEST_FILE > $seqres.full 2>&1 ||
	_fail "seek sanity check failed!"

# success, all done
status=0
exit
