#! /bin/bash
# FS QA Test No. 339
#
# Test that directory hash entries are place in the correct order.
# commit f5ea110 ("xfs: add CRCs to dir2/da node blocks") left the
# directory with incorrect hash ordering.
#
#-----------------------------------------------------------------------
# Copyright (c) 2014 Hannes Frederic Sowa.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs generic
_supported_os Linux
_require_scratch
_require_test_program "dirhash_collide"

rm -f $seqres.full
_scratch_mkfs >>$seqres.full 2>&1
_scratch_mount

echo "Silence is golden"

testdir=$SCRATCH_MNT/$seq.$$
mkdir -p $testdir
$here/src/dirhash_collide -d -n 10000 $testdir >>$seqres.full 2>&1

# check the scratch device
_scratch_unmount
_check_scratch_fs

# remove all test dirs and let test harness check scratch fs again
_scratch_mount
rm -rf $testdir

# success, all done
status=0
exit
