#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2016 SUSE Linux Products GmbH. All Rights Reserved.
#
# FSQA Test No. 340
#
# Test mmap writing races from racing threads
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment and checks
. ./common/rc

# real QA test starts here
_supported_fs generic
_supported_os Linux
_require_scratch
_require_test_program "holetest"

rm -f $seqres.full

_scratch_mkfs >>$seqres.full 2>&1
_scratch_mount

src/holetest -f $SCRATCH_MNT/testfile 1
src/holetest -f $SCRATCH_MNT/testfile 16
src/holetest -f $SCRATCH_MNT/testfile 256

status=0
exit
