#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2016 SUSE Linux Products GmbH. All Rights Reserved.
#
# FSQA Test No. 354
#
# Test races between private file mapping faults from racing processes or
# threads
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment and checks
. ./common/rc

# real QA test starts here
_supported_fs generic
_require_scratch
_require_test_program "holetest"

rm -f $seqres.full

_scratch_mkfs >>$seqres.full 2>&1
_scratch_mount

$here/src/holetest -f -p $SCRATCH_MNT/testfile 16
$here/src/holetest -f -p $SCRATCH_MNT/testfile 256
$here/src/holetest -f -p -F $SCRATCH_MNT/testfile 16
$here/src/holetest -f -p -F $SCRATCH_MNT/testfile 256

status=0
exit
