#! /bin/bash
# FS QA Test 362
#
# RichACL apply-masks test
#
#-----------------------------------------------------------------------
# Copyright (c) 2016 Red Hat, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

_supported_fs generic
_supported_os Linux

_require_scratch
_require_scratch_richacl
_require_richacl_prog

_scratch_mkfs_richacl >> $seqres.full
_scratch_mount

cd $SCRATCH_MNT

touch x
$SETRICHACL_PROG --set 'owner@:rwp::allow group@:rwp::allow everyone@:r::allow' x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'everyone@:wp::allow owner@:r::allow group@:r::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'everyone@:wp::deny owner@:rwp::allow group@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'owner@:rwCo::allow' x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'owner@:rwpCo::allow' x
$GETRICHACL_PROG x

chmod 644 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

chmod 644 x
$GETRICHACL_PROG --numeric-ids x

chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow everyone@:r::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:r::allow everyone@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:wp::deny everyone@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow u:77:wp::deny everyone@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'everyone@:rwp::allow' x
chmod 066 x
$GETRICHACL_PROG x

chmod 006 x
$GETRICHACL_PROG x

chmod 606 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow everyone@:rwp::allow' x
chmod 606 x
$GETRICHACL_PROG x

chmod 646 x
$GETRICHACL_PROG x

# success, all done
status=0
exit
