#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016 Red Hat, Inc.  All Rights Reserved.
#
# FS QA Test 362
#
# RichACL apply-masks test
#
. ./common/preamble
_begin_fstest auto quick richacl

# Import common functions.

# real QA test starts here

_supported_fs generic

_require_scratch
_require_scratch_richacl
_require_richacl_prog

_scratch_mkfs_richacl >> $seqres.full
_scratch_mount

cd $SCRATCH_MNT

touch x
$SETRICHACL_PROG --set 'owner@:rwp::allow group@:rwp::allow everyone@:r::allow' x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'everyone@:wp::allow owner@:r::allow group@:r::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'everyone@:wp::deny owner@:rwp::allow group@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'owner@:rwCo::allow' x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'owner@:rwpCo::allow' x
$GETRICHACL_PROG x

chmod 644 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

chmod 644 x
$GETRICHACL_PROG --numeric-ids x

chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow everyone@:r::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:r::allow everyone@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:wp::deny everyone@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow u:77:wp::deny everyone@:rwp::allow' x
chmod 664 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'everyone@:rwp::allow' x
chmod 066 x
$GETRICHACL_PROG x

chmod 006 x
$GETRICHACL_PROG x

chmod 606 x
$GETRICHACL_PROG x

$SETRICHACL_PROG --set 'u:77:rwp::allow everyone@:rwp::allow' x
chmod 606 x
$GETRICHACL_PROG x

chmod 646 x
$GETRICHACL_PROG x

# success, all done
status=0
exit
