#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2024 Red Hat, Inc.  All Rights Reserved.
#
# FSQA Test No. 363
#
# Run fsx with EOF pollution enabled. This provides test coverage for partial
# EOF page/block zeroing for operations that change file size.
#

. ./common/preamble
_begin_fstest rw auto

_require_test

[ $FSTYP == "btrfs" ] && _fixed_by_kernel_commit da2dccd7451d \
	"btrfs: fix hole expansion when writing at an offset beyond EOF"

# on failure, replace -q with -d to see post-eof writes in the dump output
run_fsx "-q -S 0 -e 1 -N 100000"

status=0
exit
