#! /bin/bash
# FS QA Test 364
#
# RichACL basic test
#
#-----------------------------------------------------------------------
# Copyright (c) 2016 Red Hat, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

_supported_fs generic
_supported_os Linux

_require_scratch
_require_scratch_richacl
_require_richacl_prog

_scratch_mkfs_richacl >> $seqres.full
_scratch_mount

cd $SCRATCH_MNT

umask 022

touch x

$SETRICHACL_PROG --set 'everyone@:rwp::allow' x
stat -c %A x
$GETRICHACL_PROG x

chmod 664 x
stat -c %A x
$GETRICHACL_PROG x

# Note that unlike how the test cases look at first sight, we do *not* require
# a richacl-enabled version of ls here ...

mkdir sub
$SETRICHACL_PROG --set 'everyone@:rwpxd:fd:allow' sub
stat -c %A+ sub
$GETFATTR_PROG -m system\.richacl sub

chmod 775 sub
stat -c %A+ sub
$GETFATTR_PROG -m system\.richacl sub
$GETRICHACL_PROG sub

touch sub/f
stat -c %A sub/f
$GETRICHACL_PROG sub/f

mkdir sub/sub2
stat -c %A+ sub/sub2
$GETRICHACL_PROG sub/sub2

mkdir -m 750 sub/sub3
stat -c %A+ sub/sub3
$GETRICHACL_PROG sub/sub3

# success, all done
status=0
exit
