#! /bin/bash
# FS QA Test 383
#
# Test xfs_quota when project names beginning with digits.
#
#-----------------------------------------------------------------------
# Copyright (c) 2015 Red Hat Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

qa_user=""
here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/quota

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here
_supported_fs generic
_supported_os Linux
_require_scratch
_require_quota
_require_xfs_quota_foreign

_scratch_mkfs >/dev/null 2>&1
_scratch_enable_pquota

do_project_test()
{
	local qa_project=123456-project
	local dir=$SCRATCH_MNT/project

	mkdir $dir 2>/dev/null

	#project quota files
	cat >$tmp.projects <<EOF
10:$dir
EOF

	cat >$tmp.projid <<EOF
$qa_project:10
EOF

	$XFS_QUOTA_PROG -D $tmp.projects -P $tmp.projid -x \
		-c "project -s $qa_project" $SCRATCH_MNT > /dev/null

	# We set & test inodes, because xfs vs ext4 consume differing
	# amounts of space for an empty dir, but an inode is an inode...
	$XFS_QUOTA_PROG -D $tmp.projects -P $tmp.projid -x \
		-c "limit -p isoft=100 ihard=200 $qa_project" $SCRATCH_MNT

	echo "=== quota command output ==="
	$XFS_QUOTA_PROG -D $tmp.projects -P $tmp.projid \
		-c "quota -p -v -i $qa_project" $SCRATCH_MNT | _filter_quota

	echo "=== report command output ==="
	$XFS_QUOTA_PROG -D $tmp.projects -P $tmp.projid -x \
		-c "report -p -N -i" $SCRATCH_MNT | _filter_project_quota
}

# Test project
_qmount_option "usrquota,prjquota"
_qmount
_require_prjquota $SCRATCH_DEV
do_project_test

# success, all done
status=0
exit
