#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016 Red Hat Inc.  All Rights Reserved.
#
# FS QA Test 405
#
# Test mkfs against thin provision device, which has very small backing size,
# mkfs should return error when it hits EIO.
#
. ./common/preamble
_begin_fstest auto mkfs thin

# Initialize dmthin device with very small backing size & very big virtual
# size, with the hope that mkfs hit EIO at mkfs time
BACKING_SIZE=$((1 * 1024 * 1024 / 512))			# 1M
VIRTUAL_SIZE=$((1 * 1024 * 1024 * 1024 * 1024 / 512))	# 1T

# Override the default cleanup function.
_cleanup()
{
	_dmthin_cleanup
	cd /
	rm -f $tmp.*
}

# Import common functions.
. ./common/filter
. ./common/dmthin

# real QA test starts here
_supported_fs generic
# $SCRATCH_DEV won't be directly created filesystem on, so fsck isn't required
_require_scratch_nocheck
_require_dm_target thin-pool

_dmthin_init $BACKING_SIZE $VIRTUAL_SIZE

# try mkfs on dmthin device, expect mkfs failure if 1M isn't big enough to hold
# all the metadata. But if mkfs returns success, we expect the filesystem is
# consistent, make sure it doesn't currupt silently.
$MKFS_PROG -t $FSTYP $DMTHIN_VOL_DEV >>$seqres.full 2>&1
if [ $? -eq 0 ]; then
	_dmthin_check_fs
fi

echo "Silence is golden"
status=0
exit
