#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 SUSE.  All Rights Reserved.
#
# FS QA Test No. 436
#
# More SEEK_DATA/SEEK_HOLE sanity tests.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

BASE_TEST_FILE=$TEST_DIR/seek_sanity_testfile

_cleanup()
{
	rm -f $tmp.* $BASE_TEST_FILE.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

_supported_fs generic

_require_test
_require_seek_data_hole
# All the seek sanity test cases here do falloc
_require_xfs_io_command "falloc"

_require_test_program "seek_sanity_test"

_run_seek_sanity_test -s 13 -e 16 $BASE_TEST_FILE > $seqres.full 2>&1 ||
	_fail "seek sanity check failed!"

# success, all done
echo "Silence is golden"
status=0
exit
