#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017, Jeff Layton <jlayton@redhat.com>
#
# FS QA Test No. 442
#
# Test writeback error handling when writing to block devices via pagecache.
# See src/fsync-err.c for details of what test actually does.
#
. ./common/preamble
_begin_fstest blockdev eio

# Override the default cleanup function.
_cleanup()
{
    cd /
    rm -rf $tmp.* $testdir
    _dmerror_cleanup
}

# Import common functions.
. ./common/filter
. ./common/dmerror

# real QA test starts here
_require_scratch
_require_dm_target error
_require_test_program fsync-err
_require_test_program dmerror

_dmerror_init

$here/src/fsync-err -d $here/src/dmerror $DMERROR_DEV

# success, all done
_dmerror_load_working_table
_dmerror_cleanup
_scratch_mkfs > $seqres.full 2>&1
status=0
exit
