#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2017 CTERA Networks. All Rights Reserved.
#
# FS QA Test No. 457
#
# Run fsx with log writes on cloned files to verify power fail safeness.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
status=1	# failure is the default!

_cleanup()
{
	_log_writes_cleanup
	_dmthin_cleanup
}
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink
. ./common/dmthin
. ./common/dmlogwrites

# real QA test starts here
_supported_fs generic
_require_test
_require_scratch_reflink
_require_cp_reflink
_require_log_writes
_require_dm_target thin-pool

rm -f $seqres.full

check_files()
{
	local name=$1

	# Now look for our files
	for i in $(find $SANITY_DIR -type f | grep $name | grep mark); do
		local filename=$(basename $i)
		local mark="${filename##*.}"
		echo "checking $filename" >> $seqres.full
		_log_writes_replay_log $filename $DMTHIN_VOL_DEV
		_dmthin_mount
		local expected_md5=$(_md5_checksum $i)
		local md5=$(_md5_checksum $SCRATCH_MNT/$name)
		[ "${md5}" != "${expected_md5}" ] && _fail "$filename md5sum mismatched"
		_dmthin_check_fs
	done
}

SANITY_DIR=$TEST_DIR/fsxtests
rm -rf $SANITY_DIR
mkdir $SANITY_DIR

devsize=$((1024*1024*200 / 512))        # 200m phys/virt size
csize=$((1024*64 / 512))                # 64k cluster size
lowspace=$((1024*1024 / 512))           # 1m low space threshold

# Use a thin device to provide deterministic discard behavior. Discards are used
# by the log replay tool for fast zeroing to prevent out-of-order replay issues.
_dmthin_init $devsize $devsize $csize $lowspace

# Create the log
_log_writes_init $DMTHIN_VOL_DEV

_log_writes_mkfs >> $seqres.full 2>&1

# Log writes emulates discard support, turn it on for maximum crying.
_log_writes_mount -o discard

# write testfile index -1 to be cloned to testfile0
$XFS_IO_PROG -f -c "pwrite -S 0xff 0 256k" -c "fsync" \
	$SCRATCH_MNT/testfile-1 > /dev/null 2>&1

NUM_FILES=10
NUM_OPS=10
FSX_OPTS="-N $NUM_OPS -d -k -P $SANITY_DIR -i $LOGWRITES_DMDEV"
# Run fsx for a while
# Set random seeds for fsx runs (0 for timestamp + pid)
for j in `seq 0 $((NUM_FILES-1))`; do
	# clone the clone from prev iteration which may have already mutated
	_cp_reflink $SCRATCH_MNT/testfile$((j-1)) $SCRATCH_MNT/testfile$j
	run_check $here/ltp/fsx $FSX_OPTS -S 0 -j $j $SCRATCH_MNT/testfile$j &
done
wait

test_md5=()
for j in `seq 0 $((NUM_FILES-1))`; do
	test_md5[$j]=$(_md5_checksum $SCRATCH_MNT/testfile$j)
done

# Unmount the scratch dir and tear down the log writes target
_log_writes_mark last
_log_writes_unmount
_log_writes_mark end
_log_writes_remove
_dmthin_check_fs

# check pre umount
echo "checking pre umount" >> $seqres.full
_log_writes_replay_log last $DMTHIN_VOL_DEV
_dmthin_mount
_dmthin_check_fs

for j in `seq 0 $((NUM_FILES-1))`; do
	check_files testfile$j
done

# Check the end
echo "checking post umount" >> $seqres.full
_log_writes_replay_log end $DMTHIN_VOL_DEV
_dmthin_mount
for j in `seq 0 $((NUM_FILES-1))`; do
	md5=$(_md5_checksum $SCRATCH_MNT/testfile$j)
	[ "${md5}" != "${test_md5[$j]}" ] && _fail "testfile$j end md5sum mismatched"
done

echo "Silence is golden"
status=0
exit
