#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 476
#
# Run an all-writes fsstress run with multiple threads to shake out
# bugs in the write path.
#
. ./common/preamble
_begin_fstest auto rw

# Override the default cleanup function.
_cleanup()
{
	cd /
	rm -f $tmp.*
	$KILLALL_PROG -9 fsstress > /dev/null 2>&1
}

# Import common functions.

# Modify as appropriate.
_supported_fs generic

_require_scratch
_require_command "$KILLALL_PROG" "killall"

echo "Silence is golden."

_scratch_mkfs > $seqres.full 2>&1
_scratch_mount >> $seqres.full 2>&1

nr_cpus=$((LOAD_FACTOR * 4))
nr_ops=$((25000 * nr_cpus * TIME_FACTOR))
$FSSTRESS_PROG $FSSTRESS_AVOID -w -d $SCRATCH_MNT -n $nr_ops -p $nr_cpus >> $seqres.full

# success, all done
status=0
exit
