#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2018 Oracle. All Rights Reserved.
#
# FSQA Test No. 481
#
# Reproduce a regression of btrfs that leads to -EEXIST on creating new files
# after log replay.
#
# The kernel fix is
#   Btrfs: fix unexpected -EEXIST when creating new inode
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_flakey
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/dmflakey

# real QA test starts here
_supported_fs generic
_require_scratch
_require_dm_target flakey

rm -f $seqres.full

_scratch_mkfs >>$seqres.full 2>&1
_require_metadata_journaling $SCRATCH_DEV
_init_flakey
_mount_flakey

# create a file and keep it in write ahead log
$XFS_IO_PROG -f -c "fsync" $SCRATCH_MNT/foo

# fail this filesystem so that remount can replay the write ahead log
_flakey_drop_and_remount

# see if we can create a new file successfully
touch $SCRATCH_MNT/bar

_unmount_flakey

echo "Silence is golden"

status=0
exit
