#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle.  All Rights Reserved.
#
# FS QA Test No. 522
#
# Long-soak buffered fsx test
#
. ./common/preamble
_begin_fstest soak long_rw

# Import common functions.
. ./common/filter

# real QA test starts here

# Modify as appropriate.
_supported_fs generic
_require_test

# Run fsx for a million ops or more
nr_ops=$((1000000 * TIME_FACTOR))
op_sz=$((128000 * LOAD_FACTOR))
file_sz=$((600000 * LOAD_FACTOR))
fsx_file=$TEST_DIR/fsx.$seq

fsx_args=(-q)
fsx_args+=(-N $nr_ops)
fsx_args+=(-p $((nr_ops / 100)))
fsx_args+=(-o $op_sz)
fsx_args+=(-l $file_sz)

run_fsx "${fsx_args[@]}" | sed -e '/^fsx.*/d'

# success, all done
echo Silence is golden
status=0
exit
