#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright 2019 Google LLC
#
# FS QA Test No. generic/583
#
# Verify ciphertext for v2 encryption policies that use AES-128-CBC-ESSIV to
# encrypt file contents and AES-128-CTS-CBC to encrypt file names.
#
# This is the same as generic/549, except using v2 policies.
#
. ./common/preamble
_begin_fstest auto quick encrypt

# Import common functions.
. ./common/filter
. ./common/encrypt

# real QA test starts here
_supported_fs generic

_verify_ciphertext_for_encryption_policy AES-128-CBC-ESSIV AES-128-CTS-CBC v2

# success, all done
status=0
exit
