#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright 2019 Google LLC
#
# FS QA Test No. generic/584
#
# Verify ciphertext for v2 encryption policies that use Adiantum to encrypt file
# contents and file names.
#
# This is the same as generic/550, except using v2 policies.
#
. ./common/preamble
_begin_fstest auto quick encrypt

# Import common functions.
. ./common/filter
. ./common/encrypt

# real QA test starts here
_supported_fs generic

# Test both with and without the DIRECT_KEY flag.
_verify_ciphertext_for_encryption_policy Adiantum Adiantum v2
_verify_ciphertext_for_encryption_policy Adiantum Adiantum v2 direct

# success, all done
status=0
exit
