#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 Alexander Aring.  All Rights Reserved.
#
# FS QA Test No. 740
#
# This tests performs some fcntl() corner cases. See fcntl test
# program for more details.
#
. ./common/preamble
_begin_fstest auto locks

# real QA test starts here
_supported_fs generic
_require_test
_require_test_program fcntl_lock_corner_tests

echo "Silence is golden"

rm -f $TEST_DIR/testfile
$here/src/fcntl_lock_corner_tests $TEST_DIR/testfile
if [ $? -ne 0 ]; then
	exit
fi

status=0
exit
