#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# FS QA Test 757
#
# Test async dio with fsync to test a btrfs bug where a race meant that csums
# weren't getting written to the log tree, causing corruptions on remount.
# This can be seen on subpage FSes on Linux 6.4.
#
. ./common/preamble
_begin_fstest auto quick metadata log recoveryloop aio

_cleanup()
{
	cd /
	_log_writes_cleanup &> /dev/null
	rm -f $tmp.*
}


[ $FSTYP = "btrfs" ] && _fixed_by_kernel_commit e917ff56c8e7 \
	"btrfs: determine synchronous writers from bio or writeback control"

fio_config=$tmp.fio

. ./common/dmlogwrites

_require_scratch
_require_aiodio
_require_log_writes

cat >$fio_config <<EOF
[global]
iodepth=128
direct=1
ioengine=libaio
rw=randwrite
runtime=1s
[job0]
rw=randwrite
filename=$SCRATCH_MNT/file
size=1g
fdatasync=1
EOF

_require_fio $fio_config

cat $fio_config >> $seqres.full

_log_writes_init $SCRATCH_DEV
_log_writes_mkfs >> $seqres.full 2>&1
_log_writes_mark mkfs

_log_writes_mount

$FIO_PROG $fio_config > $seqres.full 2>&1
_log_writes_unmount

_log_writes_remove

prev=$(_log_writes_mark_to_entry_number mkfs)
[ -z "$prev" ] && _fail "failed to locate entry mark 'mkfs'"
cur=$(_log_writes_find_next_fua $prev)
[ -z "$cur" ] && _fail "failed to locate next FUA write"

while _soak_loop_running $((100 * TIME_FACTOR)); do
	_log_writes_replay_log_range $cur $SCRATCH_DEV >> $seqres.full

	# xfs_repair won't run if the log is dirty
	if [ $FSTYP = "xfs" ]; then
		_scratch_mount
		_scratch_unmount
	fi
	_check_scratch_fs

	prev=$cur
	cur=$(_log_writes_find_next_fua $(($cur + 1)))
	[ -z "$cur" ] && break
done

echo "Silence is golden"

# success, all done
status=0
exit
