#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Jeff Layton <jlayton@kernel.org>.  All Rights Reserved.
#
# FS QA Test No. 786
#
# Test directory delegation support
#
. ./common/preamble
_begin_fstest auto locks quick

. ./common/filter
. ./common/locktest

_require_test
_require_test_fcntl_setdeleg

_run_dirdelegtest
_exit 0
