#! /bin/sh
# FS QA Test No. 005
#
# Test symlinks & ELOOP
#
#-----------------------------------------------------------------------
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write the Free Software Foundation, Inc., 59
# Temple Place - Suite 330, Boston MA 02111-1307, USA.
# 
# Contact information: Silicon Graphics, Inc., 1600 Amphitheatre Pkwy,
# Mountain View, CA  94043, or:
# 
# http://www.sgi.com 
# 
# For further information regarding this notice, see: 
# 
# http://oss.sgi.com/projects/GenInfo/SGIGPLNoticeExplan/
#-----------------------------------------------------------------------
#
# creator
owner=dxm@sgi.com

#
# note ELOOP limit used to be 32 but changed to 8. Who knows what
# it might be next.
#

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=0	# success is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd $testdir
    rm -f symlink_{0,1,2,3}{0,1,2,3,4,5,6,7,8,9} symlink_self empty_file
    cd /
    _cleanup_testdir
}

_touch()
{
    touch $@ 2>&1 | sed \
	-e "s/creating \`//g" \
	-e "s/setting times of \`//g" \
	-e "s/cannot touch \`//g" \
	-e "s/'//g"
}

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

# link correct .out file
_link_out_file $seq.out

# real QA test starts here
_supported_fs xfs udf nfs
_supported_os IRIX Linux

_setup_testdir

cd $testdir

o=empty_file
_touch $o
for f in symlink_{0,1,2,3}{0,1,2,3,4,5,6,7,8,9}
do
    ln -s $o $f
    o=$f
done

ln -s symlink_self symlink_self

echo "*** touch deep symlinks"
echo ""
_touch symlink_{0,1,2,3}{0,1,2,3,4,5,6,7,8,9}
echo ""
echo "*** touch recusive symlinks"
echo ""
_touch symlink_self



exit
