#! /bin/sh
# FS QA Test No. 035
#
# Test doing multiple dumps to tape and restoring the 2nd one
#
#-----------------------------------------------------------------------
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#-----------------------------------------------------------------------
#
# creator
owner=tes@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.dump

# link correct .out file
_link_out_file $seq.out

# real QA test starts here
_supported_fs xfs
_supported_os IRIX Linux

_require_tape $TAPE_DEV
_create_dumpdir_fill
_erase_hard
_do_dump -L $seq.1
_rewind
_create_dumpdir_fill2
_do_dump -L $seq.2
_do_restore -L $seq.2
_diff_compare

# success, all done
status=0
exit
