#! /bin/sh
# FS QA Test No. 041
#
# growfs QA tests - repeatedly fill/grow the filesystem
# check the filesystem contents after each operation
#
#-----------------------------------------------------------------------
# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#-----------------------------------------------------------------------
#
set +x
# creator
owner=ajag@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!

_cleanup()
{
    cd /
    umount $SCRATCH_MNT
    rm -f $tmp.*
}
trap "_cleanup ; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

# real QA test starts here
_supported_fs xfs
_supported_os IRIX Linux

_require_scratch
_require_nobigloopfs
umount $SCRATCH_DEV 2>/dev/null

_fill()
{
    if [ $# -ne 1 ]; then echo "Usage: _fill \"path\"" 1>&2 ; exit 1; fi
    _do "Fill filesystem" \
	"src/fill2fs --verbose --dir=$1 --seed=0 --filesize=65536 --stddev=32768 --list=- >>$tmp.manifest"
}

_do_die_on_error=message_only
rm -f $seq.full
agsize=32
echo -n "Make $agsize megabyte filesystem on SCRATCH_DEV and mount... "
_do "_scratch_mkfs_xfs -dsize=${agsize}m,agcount=1"
[ $? -ne 0 ] && exit
_do "_scratch_mount"
[ $? -ne 0 ] && exit
echo "done"

# full allocation group -> partial; partial -> expand partial + new partial;
# partial -> expand partial; partial -> full
# 17 -> 33 -> 35 -> 48 megabytes, converted to fs blocks below
# for size in 4352 8448 8960 12288
# 33 -> 67 -> 75 -> 96 converted to fs blocks:
for size in 8448 17512 19200 24576
do
    _fill $SCRATCH_MNT/fill_$size
    _do "Grow filesystem to $size blocks" "xfs_growfs -D ${size} $SCRATCH_MNT"
    echo -n "Flush filesystem... "
    _do "umount $SCRATCH_MNT"
    _do "_scratch_mount"
    echo "done"
    echo -n "Check files... "
    if ! _do "src/fill2fs_check $tmp.manifest"; then
      echo "fail (see $seq.full)"
      _do "cat $tmp.manifest"
      _do "ls -altrR $SCRATCH_MNT"
      _do "dd if=$SCRATCH_DEV bs=4096 count=$size | gzip -9 > $seq.fsimage.gz"
      status=1 ; exit
    fi
    echo "done"
done

# success, all done
echo "Growfs tests passed."
status=0 ; exit
