#! /bin/sh
# FS QA Test No. 043
#
# Test out xfsdump/restore but rmv inventory prior to restore.
# This checks that the on-disk inventory can be successfully
# rebuilt from the on-tape inventory.
#
#-----------------------------------------------------------------------
# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#-----------------------------------------------------------------------
#
# creator
owner=tes@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.dump

# link correct .out file
_link_out_file $seq.out

# real QA test starts here
_supported_fs xfs
_supported_os IRIX Linux

_require_tape $TAPE_DEV 
_create_dumpdir_fill
_erase_hard
_do_dump_sub
rm -rf /var/{,lib/}xfsdump/inventory # delete it - let cleanup fix it
_do_restore
_diff_compare_sub
_ls_compare_sub

# success, all done
status=0
exit
