#! /bin/sh
# FSQA Test No. 125
#
# ftruncate test, modified from CXFSQA tests cxfs_ftrunc and cxfs_trunc
#
#-----------------------------------------------------------------------
# Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------
#
# creator
owner=ajones@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    _cleanup_testdir
}

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

# real QA test starts here
_supported_fs generic
_supported_os Linux

_require_user

_setup_testdir

TESTDIR=$testdir/ftrunc
TESTFILE=$TESTDIR/ftrunc.tmp

[ -d $TESTDIR ] && rm -r $TESTDIR
mkdir $TESTDIR

# ftrunc must be run as a mortal user.
touch $TESTFILE

chmod a+rw $TESTDIR
chmod a+rw $TESTFILE

su $qa_user -c "$here/src/ftrunc -f $TESTFILE"

if [ "$?" != "0" ];  then
    echo src/ftrunc returned non 0 status!
fi

src/trunc -f $TESTFILE
if (test $? -eq 0 ) then
    status=0
fi

exit
