#! /bin/sh
# FSQA Test No. 131
#
# lock test created from CXFSQA test lockfile_simple
#
#-----------------------------------------------------------------------
#  Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#-----------------------------------------------------------------------
#
# creator
owner=allanr@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    _cleanup_testdir
}

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

# real QA test starts here
_supported_fs xfs udf nfs
_supported_os Linux

_require_user
_setup_testdir

TESTFILE=$testdir/lock_file

# Grab a port which is hopefully unused
if [ $$ -gt 1024 -a $$ -lt 32000 ]; then
    PORT=$$
elif [ $$ -lt 1024 ]; then
    PORT=$(($$+1024))
elif [ $$ -gt 32000 ]; then
    PORT=$(($$%30000+1024))
fi

# Start the server
src/locktest -p $PORT $TESTFILE > $testdir/server.out 2>&1 &

sleep 1

# Start the client
src/locktest -p $PORT -h localhost $TESTFILE > $testdir/client.out 2>&1
result=$?
if [ $result -eq 0 ]; then
    echo success!
else
    echo "Client reported failure ($result)"
    cat $testdir/*.out
    _cleanup
    exit $status
fi

status=0
exit
