#! /bin/sh
# FSQA Test No. 150
#
# Set DM_EVENT_RENAME event on a DMAPI filesystem and verify it is set.
#
#-----------------------------------------------------------------------
#  Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#-----------------------------------------------------------------------
#
# creator
owner=allanr@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    _cleanup_testdir
}

_filter_fs_handle()
{
    $SED_PROG -e "s/$DMAPI_FS_HANDLE/DMAPI_FS_HANDLE/g"
}

# get standard environment, filters and checks
. ./common.rc
. ./common.filter
. ./common.dmapi

# real QA test starts here
_supported_fs xfs
_supported_os Linux IRIX

_require_scratch
_scratch_mkfs_xfs >/dev/null 2>&1
_dmapi_scratch_mount

DMAPI_FS_HANDLE="`${DMAPI_QASUITE1_DIR}cmd/path_to_fshandle $SCRATCH_MNT`"

${DMAPI_QASUITE1_DIR}cmd/get_eventlist $DMAPI_FS_HANDLE \
    | _filter_fs_handle

${DMAPI_QASUITE1_DIR}cmd/set_eventlist $DMAPI_FS_HANDLE DM_EVENT_RENAME
echo "set_eventlist Returned: $?"

${DMAPI_QASUITE1_DIR}cmd/get_eventlist $DMAPI_FS_HANDLE \
    | _filter_fs_handle

status=0
exit 
