#! /bin/sh
# FSQA Test No. 156
#
# DMAPI get directory attributes (simple check
#
#-----------------------------------------------------------------------
#  Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#-----------------------------------------------------------------------
#
# creator
owner=allanr@sgi.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    _cleanup_testdir
}

# get standard environment, filters and checks
. ./common.rc
. ./common.filter
. ./common.dmapi

# real QA test starts here
_supported_fs xfs
_supported_os Linux IRIX

_require_scratch
_scratch_mkfs_xfs >/dev/null 2>&1
_dmapi_scratch_mount

${DMAPI_QASUITE1_DIR}cmd/get_dirattrs $SCRATCH_MNT > $seq.full
[ $? -ne 0 ] && echo "get_dirattrs failed - see $seq.full"

status=0
exit 
