#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Red Hat, Inc.  All Rights Reserved.
#
# FS QA Test No. 005
#
# Test that a bad crc on a primary V5 superblock will fail the mount
#
# 10e6e65 xfs: be more forgiving of a v4 secondary sb w/ junk in v5 fields
# inadvertently caused primary SB CRC failures to not error out, this
# is a regression test for that fix.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# Modify as appropriate.
_supported_fs xfs

_require_scratch_nocheck
_require_xfs_mkfs_crc

rm -f $seqres.full

_scratch_mkfs_xfs -m crc=1 >> $seqres.full 2>&1 || _fail "mkfs failed"

# Zap the crc.  xfs_db updates the CRC post-write, so poke it directly
$XFS_IO_PROG -c "pwrite 224 4" -c fsync $SCRATCH_DEV | _filter_xfs_io

# should FAIL, the crc is bad; golden output contains mount failure
_try_scratch_mount 2>&1 | _filter_error_mount

# success, all done
status=0
exit
