#! /bin/bash
# FS QA Test No. 022
#
# Test out a level 0 dump/restore to a tape of a subdir
# i.e. it is testing out drive_scsitape.c
#
# Use fsstress to create a directory structure with a mix of files
#
#-----------------------------------------------------------------------
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------
#

seqfull=$0
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=0	# success is the default!
trap "rm -rf $tmp.*; exit \$status" 0 1 2 3 15

. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs
_supported_os Linux

_require_tape $TAPE_DEV

# note: fsstress uses an endian dependent random number generator, running this
# will produce different output for big/little endian machines.
_create_dumpdir_stress
_erase_hard
_do_dump_sub
# filter out the file count, it changes as fsstress adds new operations
_do_restore | sed -e "/entries processed$/s/[0-9][0-9]*/NUM/g"
_ls_compare_sub

# success, all done
exit
