#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 024
#
# Test out incremental dumps
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=0	# success is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

_require_tape $TAPE_DEV
_create_dumpdir_fill
# ensure file/dir timestamps precede dump timestamp
sleep 2
$here/src/bstat $SCRATCH_MNT >>$seqres.full
_erase_hard
_do_dump
_append_dumpdir_fill
$here/src/bstat $SCRATCH_MNT >>$seqres.full
_erase_hard
_do_dump -l 1
_do_restore
_diff_compare

# success, all done
exit
