#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 035
#
# Test doing multiple dumps to tape and restoring the 2nd one
#
seqfull=$0
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

_require_tape $TAPE_DEV
_create_dumpdir_fill
_erase_hard
_do_dump -L $seq.1
_rewind
_create_dumpdir_fill2
_do_dump -L $seq.2
_do_restore -L $seq.2
_diff_compare

# success, all done
status=0
exit
