#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 055
#
# Test xfsdump/restore to a remote IRIX tape using RMT user
#
seqfull=$0
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

_require_tape $RMT_TAPE_USER@$RMT_IRIXTAPE_DEV
_create_dumpdir_fill
_erase_soft
_do_dump -o -F
_do_restore
_diff_compare

# success, all done
status=0
exit
