#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 061
#
# Test restoring a dump created in IRIX/XFS
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=0	# success is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

# src/dumpfile based on dumping from
# _create_dumpdir_fill_perm (small dump)

_create_dumpdir_fill_perm
# override dump_file to checked-in dumpfile
# we have no quotas to restore
# if we happen to run this on crackle then put the hostname back
_do_restore_file --no-check-quota -f $here/src/dumpfile -L stress_056 |
sed -e 's/HOSTNAME/crackle/g' -e 's#SCRATCH_DEV#/dev/dsk/dks0d2s1#'
_diff_compare_sub
_ls_nodate_compare_sub

# success, all done
exit
