#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 066
#
# Test dumping of large files
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/dump

_cleanup()
{
    _cleanup_dump
    cd /
    rm -f $tmp.*
}

# real QA test starts here
_supported_fs xfs
_supported_os Linux
_require_test

_my_stat_filter()
{
    grep "[sS]ize" | sed "s/.*[sS]ize[: ]*\([[:digit:]]*\).*/\1 largefile/g"
}

rm -f $TEST_DIR/testfile
if src/feature -t $TEST_DIR/testfile; then
	:
else
	_notrun "Installed libc doesn't correctly handle setrlimit/ftruncate64"
fi

_create_dumpdir_largefile
echo "ls dumpdir/largefile"
stat $dump_dir/largefile | _my_stat_filter
md5sum $dump_dir/largefile |_filter_scratch
_do_dump_file
_do_restore_file
echo "ls restoredir/largefile"
stat $restore_dir/$dump_sdir/largefile | _my_stat_filter
md5sum $restore_dir/$dump_sdir/largefile |_filter_scratch

# success, all done
status=0
exit
