#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2004 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 084
#
# Exercises unwritten extent reads and writes, looking
# for data corruption (zeroes read) near the end of file.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

_filter_resv()
{
	_filter_test_dir | sed -e 's/[0-9][0-9]* bytes/NUM bytes/g'
}

pgsize=`$here/src/feature -s`

# -i == number of iterations
# -l == bytes to leak on each iteration
# -b == read/write block size
# -s == preallocation size

# real QA test starts here
_supported_fs xfs
_supported_os Linux
_require_test

echo
echo "*** First case - I/O blocksize same as pagesize"
$here/src/resvtest -i 20 -b $pgsize "$TEST_DIR/resv" | _filter_resv
[ $? -eq 0 ] && echo done
rm -f "$TEST_DIR/mumble"

echo
echo "*** Second case - 512 byte I/O blocksize"
$here/src/resvtest -i 40 -b 512 "$TEST_DIR/resv" | _filter_resv
[ $? -eq 0 ] && echo done
rm -f "$TEST_DIR/grumble"

# success, all done
status=0
exit
