#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 131
#
# Ensure that we can't reflink realtime files.
#
. ./common/preamble
_begin_fstest auto quick clone realtime

# Override the default cleanup function.
_cleanup()
{
    cd /
    umount $SCRATCH_MNT > /dev/null 2>&1
    rm -rf $tmp.* $testdir $metadump_file
}

# Import common functions.
. ./common/filter
. ./common/reflink

# real QA test starts here
_supported_fs xfs
_require_realtime
_require_scratch_reflink
_require_cp_reflink

echo "Format and mount scratch device"
_scratch_mkfs >> $seqres.full
_scratch_mount

testdir=$SCRATCH_MNT/test-$seq
mkdir $testdir

echo "Create the original file blocks"
blksz=65536
$XFS_IO_PROG -R -f -c "truncate $blksz" $testdir/file1

echo "Reflink every block"
_cp_reflink $testdir/file1 $testdir/file2 2>&1 | _filter_scratch

test -s $testdir/file2 && _fail "Should not be able to reflink a realtime file."

# success, all done
status=0
exit
