#! /bin/bash
# FS QA Test No. 131
#
# Ensure that we can't reflink realtime files.
#
#-----------------------------------------------------------------------
# Copyright (c) 2015, Oracle and/or its affiliates.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    umount $SCRATCH_MNT > /dev/null 2>&1
    rm -rf $tmp.* $testdir $metadump_file
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink

# real QA test starts here
_supported_os Linux
_supported_fs xfs
_require_realtime
_require_scratch_reflink
_require_cp_reflink

rm -f $seqres.full

echo "Format and mount scratch device"
_scratch_mkfs >> $seqres.full
_scratch_mount

testdir=$SCRATCH_MNT/test-$seq
mkdir $testdir

echo "Create the original file blocks"
blksz=65536
$XFS_IO_PROG -R -f -c "truncate $blksz" $testdir/file1

echo "Reflink every block"
_cp_reflink $testdir/file1 $testdir/file2 2>&1 | _filter_scratch

test -s $testdir/file2 && _fail "Should not be able to reflink a realtime file."

# success, all done
status=0
exit
