#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#
# FSQA Test No. 153
#
# Associate filesystem with a session by setting DMAPI DM_EVENT_RENAME
# disposition.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/dmapi

# real QA test starts here
_supported_fs xfs

_require_scratch
_scratch_mkfs_xfs >/dev/null 2>&1
_dmapi_scratch_mount

DMAPI_FS_HANDLE="`${DMAPI_QASUITE1_DIR}cmd/path_to_fshandle $SCRATCH_MNT`"

echo "*** create DMAPI sessions"
eval `${DMAPI_QASUITE1_DIR}../simple/dm_create_session`
sid1=$newsid
eval `${DMAPI_QASUITE1_DIR}../simple/dm_create_session`
sid2=$newsid

${DMAPI_QASUITE1_DIR}cmd/set_disp -s $sid1 $DMAPI_FS_HANDLE DM_EVENT_RENAME
${DMAPI_QASUITE1_DIR}cmd/getall_disp $sid1 | $PERL_PROG -ne "s/fshandle\s+[0-9|a-f]+/fshandle FS_HANDLE/; print"
${DMAPI_QASUITE1_DIR}cmd/getall_disp $sid2

echo "*** destroy DMAPI sessions"
${DMAPI_QASUITE1_DIR}../simple/dm_destroy_session -s $sid1
${DMAPI_QASUITE1_DIR}../simple/dm_destroy_session -s $sid2

status=0
exit 
