#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#
# FSQA Test No. 157
#
# get/set DMAPI attributes
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/dmapi

# real QA test starts here
_supported_fs xfs
_supported_os Linux

_require_scratch
_scratch_mkfs_xfs >/dev/null 2>&1
_dmapi_scratch_mount

touch $SCRATCH_MNT/dmapi_test
${DMAPI_QASUITE1_DIR}cmd/set_dmattr $SCRATCH_MNT/dmapi_test ATTR_NAME_1 ATTR_VALUE_1
[ $? -ne 0 ] && echo "set_dmattr failed"
${DMAPI_QASUITE1_DIR}cmd/get_dmattr $SCRATCH_MNT/dmapi_test ATTR_NAME_1

status=0
exit 
