#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2007 Silicon Graphics, Inc.  All Rights Reserved.
#
#
# FSQA Test No. 170
#
# Check the filestreams allocator is doing its job.
# Multi-file data streams should always write into seperate AGs.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
rm -f $seqres.full
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/filestreams

# real QA test starts here
_supported_fs xfs
_supported_os Linux

_require_scratch
_require_no_rtinherit

_check_filestreams_support || _notrun "filestreams not available"

# test small stream, multiple I/O per file, 30s timeout
_set_stream_timeout_centisecs 3000

# test streams does a mkfs and mount
_test_streams 8 16 4 8 3 0 0
_test_streams 8 16 4 8 3 1 0
_test_streams 8 16 4 8 3 0 1
_test_streams 8 16 4 8 3 1 1

status=0
exit

