#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2007 Silicon Graphics, Inc.  All Rights Reserved.
#
# FSQA Test No. 172
#
# Check the filestreams allocator is doing its job.
# Multi-file data streams should always write into seperate AGs.
#
. ./common/preamble
_begin_fstest rw filestreams

# Import common functions.
. ./common/filter
. ./common/filestreams

# real QA test starts here
_supported_fs xfs

_require_scratch

_check_filestreams_support || _notrun "filestreams not available"

# test reaper works by setting timeout low. Expected to fail
# for buffered, succeed for direct I/O.
_set_stream_timeout_centisecs 50

_test_streams 8 16 4 8 3 1 0 fail
_test_streams 64 16 20 10 1 0 1

status=0
exit

