#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 233
#
# Tests xfs_growfs on a rmapbt filesystem
#
. ./common/preamble
_begin_fstest auto quick rmap

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_xfs_scratch_rmapbt
_require_no_large_scratch_dev

echo "Format and mount"
_scratch_mkfs_sized $((2 * 4096 * 4096)) > $seqres.full 2>&1
_scratch_mount >> $seqres.full 2>&1

testdir=$SCRATCH_MNT/test-$seq
mkdir $testdir

echo "Create the original files"
blksz="$(_get_block_size $testdir)"
_pwrite_byte 0x61 0 $((blksz * 14 + 71)) $testdir/original >> $seqres.full
cp -p $testdir/original $testdir/copy1
cp -p $testdir/copy1 $testdir/copy2

echo "Grow fs"
$XFS_GROWFS_PROG $SCRATCH_MNT 2>&1 |  _filter_growfs >> $seqres.full
_scratch_cycle_mount

echo "Create more copies"
cp -p $testdir/original $testdir/copy3

$XFS_INFO_PROG $SCRATCH_MNT >> $seqres.full

# success, all done
status=0
exit
