#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2011 Red Hat, Inc.  All Rights Reserved.
#
# FS QA Test No. 250
#
# Bmap btree corruption regression test
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1  # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	umount $LOOP_MNT 2>/dev/null
	rm -f $LOOP_DEV
	rmdir $LOOP_MNT
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_test
_require_loop
_require_xfs_io_command "falloc"

LOOP_DEV=$TEST_DIR/$seq.fs
LOOP_MNT=$TEST_DIR/$seq.mnt

_filter_io()
{
	sed -e '/.* ops; /d'
}

# real QA test starts here

echo "*** create loop mount point"
rmdir $LOOP_MNT 2>/dev/null
mkdir -p $LOOP_MNT || _fail "cannot create loopback mount point"

_test_loop()
{
	size=$1
	agsize=$2
	fsize=$3

	dparam="file,name=$LOOP_DEV,size=$size"
	if [ -n "$agsize" ]; then
		dparam="$dparam,agsize=$agsize"
	fi

	echo "*** mkfs loop file (size=$size)"
	$MKFS_XFS_PROG -d $dparam \
		| _filter_mkfs 2>/dev/null

	echo "*** mount loop filesystem"
	mount -t xfs -o loop $LOOP_DEV $LOOP_MNT

	echo "*** preallocate large file"
	$XFS_IO_PROG -f -c "resvsp 0 $fsize" $LOOP_MNT/foo | _filter_io

	echo "*** unmount loop filesystem"
	umount $LOOP_MNT > /dev/null 2>&1

	echo "*** check loop filesystem"
	 _check_xfs_filesystem $LOOP_DEV none none
}

_test_loop 50g 16m 40G
echo "*** done"
status=0
exit
