#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2011 SGI.  All Rights Reserved.
#
# FS QA Test No. 267
#
# Test xfsdump with a file spanning multiple media files.
#
. ./common/preamble
_begin_fstest dump ioctl tape

status=0	# success is the default!

# Override the default cleanup function.
_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

#
# create a 40 MiB file with an extended attr.
# xfsdump writes file data in "extent groups", currently 16 MiB in size. After
# writing an extent group or finishing a file, xfsdump will start a new media
# file if it is over the suggested size. With a single 40 MiB file and using a
# suggested media file size of 12 MiB below, this dump will be contained in 3
# media files.
#
_create_files()
{
    cat <<End-of-File >$tmp.config
# pathname	size            user    group    perm   name value namespace
biggg		41943040	$nobody	$nobody  777    attr1 some_text1  root
End-of-File

    _wipe_fs
    _do_create_dumpdir_fill
    _stable_fs
}

# Import common functions.
. ./common/dump
. ./common/attr

# real QA test starts here
_supported_fs xfs

_require_tape $TAPE_DEV
_require_attrs trusted

_create_files
_erase_hard
_do_dump -d 12
_do_restore
_ls_compare_sub
_diff_compare
_diff_compare_eas

# success, all done
exit
