#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2012 SGI.  All Rights Reserved.
#
# FS QA Test No. 281
#
# Test that xfsdump can generate a format 2 dump.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

_require_legacy_v2_format

_create_dumpdir_fill

echo "*** Dump using format 2"
_do_dump_file -K

echo "*** Verify it's a format 2 dump"
file $dump_file | cut -d: -f 2

echo "*** Restoring format 2 dump"
_do_restore_file
_diff_compare

# success, all done
status=0
exit
