#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 286
#
# Race fsstress and xfs_scrub in force-repair mode for a while to see if we
# crash or livelock.
#
. ./common/preamble
_begin_fstest auto online_repair fsstress_online_repair

_cleanup() {
	cd /
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

_require_scratch
_require_xfs_stress_online_repair

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_scratch_xfs_stress_online_repair -S '-k'

# success, all done
echo Silence is golden
status=0
exit
