#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2012 SGI.  All Rights Reserved.
#
# FS QA Test No. 290
#
# Makes calls to XFS_IOC_ZERO_RANGE and checks tossed ranges
#
# Nothing should be tossed unless the range includes a page boundry
#
# Primarily tests page boundries and boundries that are
#  off-by-one to ensure we're only tossing what's expected
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/punch

# real QA test starts here

# Modify as appropriate.
_supported_fs xfs

_require_test
_require_xfs_io_command "zero"

testfile=$TEST_DIR/290.$$

_test_block_boundaries 4096 zero _filter_xfs_io_unique $testfile

# success, all done
status=0
exit
