#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 326
#
# Reflink a file with a few dozen extents, CoW a few blocks, and rm.
# Inject an error during refcount updates to test log recovery.  Use
# cowextsize so that the refcount failure is somewhere in the CoW remap
# instead of when we're stashing the CoW orphan record.
#
. ./common/preamble
_begin_fstest auto quick clone punch

# Override the default cleanup function.
_cleanup()
{
	cd /
	_scratch_unmount > /dev/null 2>&1
	rm -rf $tmp.*
}

# Import common functions.
. ./common/filter
. ./common/reflink
. ./common/inject

# real QA test starts here
_supported_fs xfs
_require_cp_reflink
_require_scratch_reflink
_require_xfs_io_command "cowextsize"
_require_xfs_io_command "fpunch"
_require_xfs_io_error_injection "refcount_finish_one"

blksz=65536
blks=64
sz=$((blksz * blks))
echo "Format filesystem"
_scratch_mkfs >/dev/null 2>&1
_scratch_mount >> $seqres.full

_require_congruent_file_oplen $SCRATCH_MNT $blksz
$XFS_IO_PROG -c "cowextsize $sz" $SCRATCH_MNT

# This test uses a very large cowextszhint to manipulate the COW fork to
# contain a large unwritten extent before injecting the error.  The goal is
# that the write() will succeed, writeback will flush the dirty data to disk,
# and writeback completion will shut down the filesystem when it tries to
# remove the staging extent record from the refcount btree.  In other words,
# this test ensures that XFS always finishes a COW completion it has started.
#
# This test isn't compatible with always_cow mode because the hole in the COW
# fork left by the first write means that writeback tries to allocate a COW
# staging extent for an unshared extent and trips over the injected error.
_require_no_xfs_always_cow

echo "Create files"
_pwrite_byte 0x66 0 $sz $SCRATCH_MNT/file1 >> $seqres.full
_cp_reflink $SCRATCH_MNT/file1 $SCRATCH_MNT/file2
_cp_reflink $SCRATCH_MNT/file1 $SCRATCH_MNT/file3

# Punch holes in file3
seq 1 2 $blks | while read off; do
	$XFS_IO_PROG -c "fpunch $((off * blksz)) $blksz" $SCRATCH_MNT/file3 >> $seqres.full
done
sync

echo "Check files"
md5sum $SCRATCH_MNT/file1 | _filter_scratch
md5sum $SCRATCH_MNT/file2 | _filter_scratch
md5sum $SCRATCH_MNT/file3 | _filter_scratch

$XFS_IO_PROG -c "pwrite -W -S 0x67 $((10 * blksz)) 1" $SCRATCH_MNT/file2 >> $seqres.full
sync

echo "Inject error"
_scratch_inject_error "refcount_finish_one"

echo "CoW a few blocks"
$XFS_IO_PROG -c "pwrite -W -S 0x67 -b $sz $((10 * blksz)) $((10 * blksz))" $SCRATCH_MNT/file2 >> $seqres.full 2>&1

echo "FS should be shut down, touch will fail"
touch $SCRATCH_MNT/badfs 2>&1 | _filter_scratch

echo "Remount to replay log"
_scratch_remount_dump_log >> $seqres.full

echo "FS should be online, touch should succeed"
touch $SCRATCH_MNT/goodfs

echo "Check files again"
md5sum $SCRATCH_MNT/file1 | _filter_scratch
md5sum $SCRATCH_MNT/file2 | _filter_scratch
md5sum $SCRATCH_MNT/file3 | _filter_scratch

echo "Done"

# success, all done
status=0
exit
