#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 333
#
# Set rrmapino to another inode on an non-rt rmap fs and see if repair fixes it.
#
. ./common/preamble
_begin_fstest auto quick rmap realtime

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_xfs_scratch_rmapbt
_disable_dmesg_check

rm -f "$seqres.full"

unset SCRATCH_RTDEV

echo "Format and mount"
_scratch_mkfs > "$seqres.full" 2>&1
rrmapino="$(_scratch_xfs_db -c 'sb 0' -c 'p rrmapino' 2>&1)"
test "${rrmapino}" = "field rrmapino not found" && _notrun "realtime rmapbt not supported"
_scratch_mount

echo "Create some files"
$XFS_IO_PROG -f -c "pwrite -S 0x68 0 9999" $SCRATCH_MNT/f1 >> $seqres.full
$XFS_IO_PROG -f -c "pwrite -S 0x68 0 9999" $SCRATCH_MNT/f2 >> $seqres.full
echo garbage > $SCRATCH_MNT/f3
ino=$(stat -c '%i' $SCRATCH_MNT/f3)
_scratch_unmount

echo "Corrupt fs"
_scratch_xfs_db -x -c 'sb 0' -c "write rrmapino $ino" >> $seqres.full
_try_scratch_mount 2>&1 | _filter_error_mount

echo "Test done, mount should have failed"

# success, all done
status=0
exit
