#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 339
#
# Link rrmapino into the rootdir on an rtrmap fs and see if repair fixes it.
#
. ./common/preamble
_begin_fstest auto quick rmap realtime repair

# Import common functions.
. ./common/filter

_require_realtime
_require_xfs_scratch_rmapbt

rm -f "$seqres.full"

echo "Format and mount"
_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount

echo "Create some files"
$XFS_IO_PROG -f -R -c "pwrite -S 0x68 0 9999" $SCRATCH_MNT/f1 >> $seqres.full
$XFS_IO_PROG -f -R -c "pwrite -S 0x68 0 9999" $SCRATCH_MNT/f2 >> $seqres.full
echo garbage > $SCRATCH_MNT/f3
ln $SCRATCH_MNT/f3 $SCRATCH_MNT/f4
_scratch_unmount

echo "Corrupt fs"
rrmapino=$(_scratch_metadir_lookup /rtgroups/0.rmap)
test -n "$rrmapino" || _fail "Could not find rtrmap inode?"
_scratch_xfs_set_metadata_field "u3.sfdir3.list[3].inumber.i4" $rrmapino \
	'sb 0' 'addr rootino' >> $seqres.full
_scratch_mount

echo "Check files"
md5sum $SCRATCH_MNT/f1 2>&1 | _filter_scratch

echo "Try to create more files"
$XFS_IO_PROG -f -R -c "pwrite -S 0x68 0 9999" $SCRATCH_MNT/f5 >> $seqres.full 2>&1

echo "Repair fs"
_scratch_unmount 2>&1 | _filter_scratch | _filter_ending_dot
_repair_scratch_fs >> $seqres.full 2>&1

echo "Try to create more files (again)"
_scratch_mount
$XFS_IO_PROG -f -R -c "pwrite -S 0x68 0 9999" $SCRATCH_MNT/f4 >> $seqres.full

# success, all done
status=0
exit
