#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 367
#
# Populate a XFS filesystem and fuzz every finobt field.
# Use xfs_scrub to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers scrub fuzzers_online_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_scratch_xfs_fuzz_fields
_require_xfs_finobt

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

path="$(_scratch_xfs_find_agbtree_height 'fino' 2)" || \
	_fail "could not find two-level finobt"

echo "Fuzz finobt"
_scratch_xfs_fuzz_metadata '' 'online'  "$path" 'addr free_root' 'addr ptrs[1]' >> $seqres.full
echo "Done fuzzing finobt"

# success, all done
status=0
exit
