#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 396
#
# Populate a XFS filesystem and fuzz every freeindex-format dir block field.
# Use xfs_repair to fix the corruption.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_os Linux
_supported_fs xfs
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Find freeindex-format dir block"
_scratch_mount
inum=$(stat -c '%i' $SCRATCH_MNT/S_IFDIR.FMT_NODE)
blk_sz=$(_get_block_size $SCRATCH_MNT)
_scratch_unmount

leaf_offset=$(( (2 ** 36) / blk_sz ))
echo "Fuzz freeindex-format dir block"
_scratch_xfs_fuzz_metadata '' 'offline'  "inode ${inum}" "dblock ${leaf_offset}" >> $seqres.full
echo "Done fuzzing freeindex-format dir block"

# success, all done
status=0
exit
