#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 401
#
# Populate a XFS filesystem and fuzz every leaf-format attr block field.
# Use xfs_scrub to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers scrub fuzzers_online_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Find leaf-format attr block"
_scratch_mount
inum=$(stat -c '%i' $SCRATCH_MNT/ATTR.FMT_LEAF)
_scratch_unmount

echo "Fuzz leaf-format attr block"
_scratch_xfs_fuzz_metadata '' 'online'  "inode ${inum}" 'ablock 0' >> $seqres.full
echo "Done fuzzing leaf-format attr block"

# success, all done
status=0
exit
