#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 406
#
# Populate a XFS filesystem and fuzz every rtrmapbt record field.
# Use xfs_repair to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers repair fuzzers_repair realtime

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_realtime
_require_xfs_scratch_rmapbt
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

path="$(_scratch_xfs_find_rgbtree_height 'rmap' 2)" || \
	_fail "could not find two-level rtrmapbt"
inode_ver=$(_scratch_xfs_get_metadata_field "core.version" "path -m $path")

echo "Fuzz rtrmapbt recs"
_scratch_xfs_fuzz_metadata '' 'offline' "path -m $path" "addr u${inode_ver}.rtrmapbt.ptrs[1]" >> $seqres.full
echo "Done fuzzing rtrmapbt recs"

# success, all done
status=0
exit
