#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 409
#
# Populate a XFS filesystem and fuzz every rtrmapbt keyptr field.
# Use xfs_scrub to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers scrub fuzzers_online_repair realtime

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_realtime
_require_xfs_scratch_rmapbt
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz rtrmapbt keyptrs"
_scratch_xfs_fuzz_metadata '(rtrmapbt)' 'offline' 'sb 0' 'addr rrmapino' >> $seqres.full
echo "Done fuzzing rtrmapbt keyptrs"

# success, all done
status=0
exit
