#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 411
#
# Populate a XFS filesystem and fuzz every refcountbt field.
# Use xfs_scrub to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_scrub fuzzers_online_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/reflink

_require_scratch_reflink
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

path="$(_scratch_xfs_find_agbtree_height 'refcnt' 2)" || \
	_fail "could not find two-level refcountbt"

echo "Fuzz refcountbt"
_scratch_xfs_fuzz_metadata '' 'online'  "$path" 'addr refcntroot' 'addr ptrs[1]' >> $seqres.full
echo "Done fuzzing refcountbt"

# success, all done
status=0
exit
