#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 412
#
# Populate a XFS filesystem and fuzz every btree-format attr inode field.
# Use xfs_repair to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_scrub fuzzers_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Find btree-format attr inode"
_scratch_mount
inum=$(stat -c '%i' $SCRATCH_MNT/ATTR.FMT_BTREE)
_scratch_unmount

echo "Fuzz inode"
_scratch_xfs_fuzz_metadata '' 'offline'  "inode ${inum}" >> $seqres.full
echo "Done fuzzing inode"

# success, all done
status=0
exit
