#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 419
#
# Check that we can't swapon a realtime file.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_realtime
_require_scratch_swapfile

echo "Format and mount"
_scratch_mkfs > $seqres.full 2>&1
_scratch_mount >> $seqres.full 2>&1

testdir=$SCRATCH_MNT/test-$seq
mkdir $testdir

blocks=160
blksz=65536

echo "Initialize file"
echo >> $seqres.full
$XFS_IO_PROG -c "open -f -R $testdir/dummy" $testdir >> $seqres.full
echo moo >> $testdir/dummy
$XFS_IO_PROG -c "open -f -R $testdir/file1" $testdir >> $seqres.full
_pwrite_byte 0x61 0 $((blocks * blksz)) $testdir/file1 >> $seqres.full
$MKSWAP_PROG -U 27376b42-ff65-42ca-919f-6c9b62292a5c $testdir/file1 >> $seqres.full

echo "Try to swapon"
swapon $testdir/file1 2>&1 | _filter_scratch

swapoff $testdir/file1 >> $seqres.full 2>&1

# success, all done
status=0
exit
