#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 422
#
# Race fsstress and rmapbt repair for a while to see if we crash or livelock.
# rmapbt repair requires us to freeze the filesystem to stop all filesystem
# activity, so we can't have userspace wandering in and thawing it.
#
. ./common/preamble
_begin_fstest online_repair dangerous_fsstress_repair freeze

_cleanup() {
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	cd /
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/inject

# real QA test starts here
_supported_fs xfs
_require_scratch
_require_xfs_stress_online_repair

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_require_xfs_has_feature "$SCRATCH_MNT" rmapbt
_scratch_xfs_stress_online_repair -f -s "repair rmapbt %agno%"

# success, all done
echo Silence is golden
status=0
exit
