#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 428
#
# Populate a XFS filesystem and fuzz every group dquot field.
# Use xfs_scrub to fix the corruption.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/quota

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_require_quota

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1
echo "${MOUNT_OPTIONS}" | grep -q 'grpquota' || _notrun "group quota disabled"

echo "Fuzz group 0 dquot"
_scratch_xfs_fuzz_metadata '' 'online'  "dquot -g 0" >> $seqres.full
echo "Done fuzzing dquot"

# success, all done
status=0
exit
