#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 428
#
# Populate a XFS filesystem and fuzz every group dquot field.
# Use xfs_scrub to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_scrub dangerous_online_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/quota

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_require_quota

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1
echo "${MOUNT_OPTIONS}" | grep -q 'grpquota' || _notrun "group quota disabled"

echo "Fuzz group 0 dquot"
_scratch_xfs_fuzz_metadata '' 'online'  "dquot -g 0" >> $seqres.full
echo "Done fuzzing dquot"

# success, all done
status=0
exit
