#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle, Inc.  All rights reserved.
#
# FS QA Test No. 464
#
# Populate a XFS filesystem and fuzz every refcountbt field.
# Do not fix the filesystem, to test metadata verifiers.

. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_norepair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/reflink

# real QA test starts here
_supported_fs xfs
_require_scratch_reflink
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz refcountbt"
_scratch_xfs_fuzz_metadata '' 'none'  'agf 0' 'addr refcntroot' >> $seqres.full
echo "Done fuzzing refcountbt"

# success, all done
status=0
exit
