#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle, Inc.  All rights reserved.
#
# FS QA Test No. 477
#
# Populate a XFS filesystem and fuzz every inline attr inode field.
# Do not fix the filesystem, to test metadata verifiers.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Find inline-format attr inode"
_scratch_mount
inum=$(stat -c '%i' $SCRATCH_MNT/ATTR.FMT_LOCAL)
_scratch_unmount

echo "Fuzz inline-format attr inode"
_scratch_xfs_fuzz_metadata '' 'none'  "inode ${inum}" >> $seqres.full
echo "Done fuzzing inline-format attr inode"

# success, all done
status=0
exit
