#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle, Inc.  All rights reserved.
#
# FS QA Test No. 482
#
# Populate a XFS filesystem and fuzz every rtrmapbt key/pointer field.
# Do not fix the filesystem, to test metadata verifiers.

. ./common/preamble
_begin_fstest dangerous_fuzzers fuzzers_norepair realtime

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_realtime
_require_xfs_scratch_rmapbt
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

path="$(_scratch_xfs_find_rgbtree_height 'rmap' 2)" || \
	_fail "could not find two-level rtrmapbt"

echo "Fuzz rtrmapbt keyptrs"
_scratch_xfs_fuzz_metadata '(rtrmapbt)' 'offline' "path -m $path" >> $seqres.full
echo "Done fuzzing rtrmapbt keyptrs"

# success, all done
status=0
exit
