#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test No. 563
#
# Race xfs_scrub in force-repair mdoe and freeze for a while to see if we crash
# or livelock.
#
. ./common/preamble
_begin_fstest online_repair fsstress_online_repair

# Override the default cleanup function.
_cleanup()
{
	cd /
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	_scratch_remount rw
	rm -rf $tmp.*
}

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/xfs
. ./common/inject

_require_scratch
_require_xfs_stress_online_repair

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_scratch_xfs_stress_online_repair -f -S '-k'

# success, all done
echo "Silence is golden"
status=0
exit
