#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 Oracle. Inc.  All Rights Reserved.
#
# FS QA Test No. 582
#
# Race fsstress and realtime summary scrub for a while to see if we crash or
# livelock.
#
. ./common/preamble
_begin_fstest scrub fsstress_scrub

_cleanup() {
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	cd /
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

_require_realtime
_require_scratch
_require_xfs_stress_scrub

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_require_xfs_has_feature "$SCRATCH_MNT" realtime

# XXX the realtime summary scrubber isn't currently implemented upstream.
# Don't bother trying to test it on those kernels
$XFS_IO_PROG -c 'scrub rtsummary' -c 'scrub rtsummary' "$SCRATCH_MNT" 2>&1 | \
	grep -q 'Scan was not complete' && \
	_notrun "rtsummary scrub is incomplete"

_scratch_xfs_stress_scrub -s "scrub rtsummary"

# success, all done
echo Silence is golden
status=0
exit
