#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test No. 728
#
# Race fsstress and inode link count repair for a while to see if we crash or
# livelock.
#
. ./common/preamble
_begin_fstest online_repair fsstress_online_repair

_cleanup() {
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	cd /
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

_require_scratch
_require_xfs_stress_online_repair

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_scratch_xfs_stress_online_repair -x "dir" -s "repair nlinks"

# success, all done
echo Silence is golden
status=0
exit
