#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test No. 742
#
# Populate a XFS filesystem and fuzz every realtime summary field.
# Use xfs_repair to fix the corruption.

. ./common/preamble
_begin_fstest dangerous_fuzzers repair fuzzers_repair realtime

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_realtime
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz rtsummary"
is_metadir=$(_scratch_xfs_get_metadata_field "core.version" 'path -m /realtime/0.summary')
if [ -n "$is_metadir" ]; then
	path=('path -m /realtime/0.summary')
else
	path=('sb' 'addr rsumino')
fi
_scratch_xfs_fuzz_metadata '' 'offline' "${path[@]}" 'dblock 0' >> $seqres.full
echo "Done fuzzing rtsummary"

# success, all done
status=0
exit
