#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test No. 745
#
# Populate a XFS filesystem and fuzz every realtime bitmap field.
# Do not fix the filesystem, to test metadata verifiers.

. ./common/preamble
_begin_fstest dangerous_fuzzers fuzzers_norepair realtime

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_realtime
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz rtbitmap"
path="$(_scratch_xfs_find_metafile rbmino)"
_scratch_xfs_fuzz_metadata '' 'none' "$path" 'dblock 0' >> $seqres.full
echo "Done fuzzing rtbitmap"

# success, all done
status=0
exit
