#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test No. 759
#
# Populate a XFS filesystem and fuzz every btree-format directory inode field.
# Try online repair and, if necessary, offline repair,
# to test the most likely usage pattern.

. ./common/preamble
_begin_fstest dangerous_fuzzers scrub repair fuzzers_bothrepair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Find btree-format dir inode"
_scratch_mount
inum=$(stat -c '%i' $SCRATCH_MNT/S_IFDIR.FMT_BTREE)
_scratch_unmount

echo "Fuzz inode"
_scratch_xfs_fuzz_metadata '' 'both'  "inode ${inum}" >> $seqres.full
echo "Done fuzzing inode"

# success, all done
status=0
exit
