#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 800
#
# Race fsstress doing mostly renames and xfs_scrub in read-only mode for a
# while to see if we crash or livelock.
#
. ./common/preamble
_begin_fstest scrub fsstress_scrub

_cleanup() {
	cd /
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

_require_scratch
_require_xfs_stress_scrub

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_scratch_xfs_stress_scrub -S '-n' -x 'parent'

# success, all done
echo Silence is golden
status=0
exit
