#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022-2025 Oracle.  All Rights Reserved.
#
# FS QA Test No. 823
#
# Race fsstress and realtime bitmap repair for a while to see if we crash or
# livelock.
#
. ./common/preamble
_begin_fstest online_repair fsstress_online_repair

_cleanup() {
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	cd /
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

_require_realtime
_require_scratch
_require_xfs_stress_online_repair

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_require_xfs_has_feature "$SCRATCH_MNT" realtime
_xfs_force_bdev realtime $SCRATCH_MNT

if _xfs_has_feature "$SCRATCH_MNT" rtgroups; then
	_scratch_xfs_stress_online_repair -s "repair rtbitmap %rgno%"
elif xfs_io -c 'help scrub' | grep -q rgsuper; then
	_scratch_xfs_stress_online_repair -s "repair rtbitmap 0"
else
	_scratch_xfs_stress_online_repair -s "repair rtbitmap"
fi

# success, all done
echo Silence is golden
status=0
exit
