#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022-2025 Oracle.  All Rights Reserved.
#
# FS QA Test No. 835
#
# Race fsstress and rt refcount btree scrub for a while to see if we crash or
# livelock.
#
. ./common/preamble
_begin_fstest scrub fsstress_scrub

_cleanup() {
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	cd /
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

_require_realtime
_require_scratch
_require_xfs_stress_scrub

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_require_xfs_has_feature "$SCRATCH_MNT" realtime
_require_xfs_has_feature "$SCRATCH_MNT" reflink
_xfs_force_bdev realtime $SCRATCH_MNT

_scratch_xfs_stress_scrub -s "scrub rtrefcountbt %rgno%"

# success, all done
echo Silence is golden
status=0
exit
