#!/bin/ksh
#
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#

sr_dir=$1
shift 1

for i in $*
  do
  attr -Rq -s SGI_DMI_test -V123456789abcdefghijklmnopqrstuvwxyz $i 
  $sr_dir/set_region $i DM_REGION_READ DM_REGION_WRITE DM_REGION_TRUNCATE > /dev/null
  done
