#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Fujitsu.  All Rights Reserved.
#
# FS QA Test No. btrfs/033
#
# Regression test for iterating backrefs
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!

_cleanup()
{
    rm -f $tmp.*
}

trap "_cleanup ; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs btrfs
_require_scratch

_scratch_mkfs > /dev/null 2>&1
_scratch_mount

touch $SCRATCH_MNT/foo

# get file with fragments by using backwards writes.
for i in `seq 10240 -1 1`; do
	$XFS_IO_PROG -f -d -c "pwrite $(($i * 4096)) 4096" \
		$SCRATCH_MNT/foo > /dev/null
done

# get some snapshots here to make sure we are really
# suffering from walking backrefs.
for i in `seq 0 50`; do
	$BTRFS_UTIL_PROG subvolume snapshot -r $SCRATCH_MNT \
		$SCRATCH_MNT/snap_$i >> $seqres.full 2>&1
done

$BTRFS_UTIL_PROG send -f $SCRATCH_MNT/send_file \
	$SCRATCH_MNT/snap_1 >> $seqres.full 2>&1

echo "Silence is golden"
status=0 ; exit
