#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2016 SUSE Linux Products GmbH. All Rights Reserved.
#
# FSQA Test No. 120
#
# Test that if we delete a snapshot, delete its parent directory, create
# another directory with the same name as that parent and then fsync either
# the new directory or a file inside the new directory, the fsync succeeds,
# the fsync log is replayable and produces a correct result.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_flakey
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/dmflakey

# real QA test starts here
_supported_fs btrfs
_supported_os Linux
_require_scratch
_require_dm_target flakey

rm -f $seqres.full

populate_testdir()
{
	_run_btrfs_util_prog subvolume snapshot $SCRATCH_MNT \
		$SCRATCH_MNT/testdir/snap
	_run_btrfs_util_prog subvolume delete $SCRATCH_MNT/testdir/snap
	rmdir $SCRATCH_MNT/testdir
	mkdir $SCRATCH_MNT/testdir
}

_scratch_mkfs >>$seqres.full 2>&1
_require_metadata_journaling $SCRATCH_DEV
_init_flakey
_mount_flakey

mkdir $SCRATCH_MNT/testdir
populate_testdir
$XFS_IO_PROG -c "fsync" $SCRATCH_MNT/testdir
_flakey_drop_and_remount

echo "Filesystem contents after the first log replay:"
ls -R $SCRATCH_MNT | _filter_scratch

# Now do the same as before but instead of doing an fsync against the directory,
# do an fsync against a file inside the directory.

populate_testdir
touch $SCRATCH_MNT/testdir/foobar
$XFS_IO_PROG -c "fsync" $SCRATCH_MNT/testdir/foobar
_flakey_drop_and_remount

echo "Filesystem contents after the second log replay:"
ls -R $SCRATCH_MNT | _filter_scratch

_unmount_flakey
status=0
exit
