#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019 SUSE Linux Products GmbH. All Rights Reserved.
#
# FS QA Test 182
#
# Test if balance will report false ENOSPC error
#
# This is a long existing bug, caused by over-estimated metadata
# space_info::bytes_may_use.
#
# There is one proposed patch for btrfs-progs to fix it, titled:
# "btrfs-progs: balance: Sync the fs before balancing metadata chunks"
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs btrfs
_supported_os Linux
_require_scratch

nr_files=1024

_scratch_mkfs > /dev/null
_scratch_mount

$BTRFS_UTIL_PROG subvolume create "$SCRATCH_MNT/subvol" > /dev/null

# Create some small files to take up enough metadata reserved space
for ((i = 0; i < $nr_files; i++)) do
	_pwrite_byte 0xcd 0 1K "$SCRATCH_MNT/subvol/file_$i" > /dev/null
done

$BTRFS_UTIL_PROG balance start -m "$SCRATCH_MNT" > /dev/null

# success, all done
echo "Silence is golden"
status=0
exit
