#!/bin/bash
#-----------------------------------------------------------------------
# Copyright (c) 2017, Jeff Layton <jlayton@redhat.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------

. ./common/config
. ./common/dmerror

_dmerror_setup

case $1 in
cleanup)
	_dmerror_cleanup
	;;
init)
	_dmerror_init
	;;
load_error_table)
	_dmerror_load_error_table
	;;
load_working_table)
	_dmerror_load_working_table
	;;
*)
	echo "Usage: $0 {init|cleanup|load_error_table|load_working_table}"
	exit 1
	;;
esac

status=0
exit
