#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017, Jeff Layton <jlayton@redhat.com>

. ./common/config
. ./common/dmerror

_dmerror_setup

case $1 in
cleanup)
	_dmerror_cleanup
	;;
init)
	_dmerror_init
	;;
load_error_table)
	_dmerror_load_error_table
	;;
load_working_table)
	_dmerror_load_working_table
	;;
*)
	echo "Usage: $0 {init|cleanup|load_error_table|load_working_table}"
	exit 1
	;;
esac

status=0
exit
