#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016 Red Hat Inc.  All Rights Reserved.
#
# FS QA Test 007
#
# Test getcwd() failure after unsuccessful rmdir
#
# Upstream commit ce9113bbcbf4 ("ovl: fix getcwd() failure after unsuccessful
# rmdir") fixed this issue
#
. ./common/preamble
_begin_fstest auto quick

# Override the default cleanup function.
_cleanup()
{
	cd /
	rm -f $tmp.*
	rm -rf $TEST_DIR/$seq
}

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs overlay
_require_test

rm -rf $TEST_DIR/$seq

# make a non-empty dir $seq
mkdir -p $TEST_DIR/$seq/$seq.sub
# cd to it and call rmdir on it, rmdir should fail
cd $TEST_DIR/$seq
rmdir ../$seq >>$seqres.full 2>&1
# getcwd should return the correct current dir
pwd | _filter_test_dir

# success, all done
status=0
exit
