#! /bin/bash
# FS QA Test 024
#
# "work" directory under workdir should be cleaned up
# well on overlayfs startup, or overlayfs will be mounted
# read-only.
# Kernel commit below fixes it.
# eea2fb4851e9 ovl: proper cleanup of workdir
#
# This reproducer was originally written by
#     Miklos Szeredi <mszeredi@redhat.com>
#
#-----------------------------------------------------------------------
# Copyright (c) 2017 Red Hat Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs overlay
_supported_os Linux
_require_scratch

# Remove all files from previous tests
_scratch_mkfs

# making workdir
wkdir=$OVL_BASE_SCRATCH_MNT/$OVL_WORK
mkdir -p $wkdir/work/foo

_scratch_mount

# try writing to mountpoint
touch $SCRATCH_MNT/bar

# checking work dir is clean
if [ -e $wkdir/work/foo ] ; then
	echo "work dir is not clean"
else
	echo "Silence is golden"
fi
# success, all done
status=0
exit
