#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 CTERA Networks. All Rights Reserved.
#
# FS QA Test 106
#
# Run unionmount testsuite to verify correctness
# with multi lower layers, some layers on unique fs,
# one layer is on tmpfs.
#
. ./common/preamble
_begin_fstest auto union rotate nonsamefs

_register_cleanup "_unionmount_testsuite_cleanup"

# Import common functions.
. ./common/filter

# real QA test starts here

_supported_fs overlay
_require_extra_fs tmpfs
_require_test
_require_scratch
_require_unionmount_testsuite

_unionmount_testsuite_run --ov=10 --maxfs=1 --verify

# success, all done
echo "Silence is golden"
status=0
exit
