#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 CTERA Networks. All Rights Reserved.
#
# FS QA Test 107
#
# Run unionmount testsuite to verify correctness
# with multi lower layers, some layers on unique fs,
# one layer is on tmpfs with xino enabled.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_unionmount_testsuite_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

_supported_fs overlay
_require_extra_fs tmpfs
_require_test
_require_scratch
_require_unionmount_testsuite

_unionmount_testsuite_run --ov=10 --maxfs=1 --xino --verify

# success, all done
echo "Silence is golden"
status=0
exit
