#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 CTERA Networks. All Rights Reserved.
#
# FS QA Test 110
#
# Run unionmount testsuite on a nested overlay filesystem
# with single lower overlay layer, whose layers are
# on same fs
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_unionmount_testsuite_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

_supported_fs overlay
_require_scratch
_require_unionmount_testsuite

_unionmount_testsuite_run --ovov --samefs --verify

# success, all done
echo "Silence is golden"
status=0
exit
