#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Chao Yu.  All Rights Reserved.
#
# FS QA Test No. f2fs/021
#
# This testcase tries to check whether f2fs can handle "usrjquota="
# during remount correctly
#
. ./common/preamble
_begin_fstest auto quick mount quota remount

_fixed_by_kernel_commit xxxxxxxxxxxx \
	"f2fs: fix to avoid NULL pointer dereference in f2fs_check_quota_consistency()"

_require_scratch

_scratch_mkfs >> $seqres.full
_scratch_mount "-o usrquota"
quotacheck -uc $SCRATCH_MNT
_scratch_unmount

_scratch_mount "-o usrjquota=aquota.user,jqfmt=vfsold"
_scratch_mount "-o remount,usrjquota=,jqfmt=vfsold"
_scratch_unmount

echo "Silence is golden"

status=0
exit
